version: '3.8'

services:
  web:
    build: .
    container_name: usermanagementapp-web
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=usermanagementdb;Username=myappuser;Password=strongpassword
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/app
    
  db:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_USER=myappuser
      - POSTGRES_PASSWORD=strongpassword
      - POSTGRES_DB=usermanagementdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data:
